version: '3'
services:
  web:
    image: helloworld:latest
    ports:
      - "80:80"

  database:
    image: mysql2:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
